  // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoIpxxlig2r-VrBWN9SvvsxOaM69MiqXs',
    appId: '1:1037991048727:web:959da6bc112f24f14ece52',
    messagingSenderId: '1037991048727',
    projectId: 'hotelexpenses-3719c',
    authDomain: 'hotelexpenses-3719c.firebaseapp.com',
    storageBucket: 'hotelexpenses-3719c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSV8mPmlQg3hM2hY4EZo9HLDi70J8vWNw',
    appId: '1:1037991048727:android:04e8a58bd39a637b4ece52',
    messagingSenderId: '1037991048727',
    projectId: 'hotelexpenses-3719c',
    storageBucket: 'hotelexpenses-3719c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfmn2CYVhUUkSUHQMeBtN0NxkVB0WKAgA',
    appId: '1:1037991048727:ios:205983fbf09ea6724ece52',
    messagingSenderId: '1037991048727',
    projectId: 'hotelexpenses-3719c',
    storageBucket: 'hotelexpenses-3719c.firebasestorage.app',
    iosBundleId: 'com.example.hotelexpenses',
  );
}
