import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:hotelexpenses/View/homepage.dart';
import 'package:hotelexpenses/View/product_view.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI


// ----------- Main Page -----------
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Hotel Expenses',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: HomePage(),
    );
  }
}
